export const projects = [
  {
    title: ' Mobile Robot',
    description: "Worked on an autonomous rover that is designed to face martian terrain, it uses navigation algorithms like A* and Atrificial Potential Field, EKF for building the maps , AR tag and Arrow detection for localization and task completetion indicator.",
      image: '/images/amr.png',
      tags: ['ROS', 'Gazebo', 'OpenCV'],
    source: 'https://google.com',
    visit: 'https://github.com/Menon-Madhav/Mobile-Robots',
    id: 0,
  },
  {
    title: 'Digital Twin in Additive Manufacturing',
    description:"Building a virtual twin of a real life component(3D printer) so as to be able to oversee various functionalities like tool maintenance, product quality, lool for defects. The real life model is connected to the virtual model through TCP/IP protocols  which help in sending feedbacks from the model to the printer autonomously",
    image: '/images/3dprinter.png',
    tags: ['Anylogic', 'Matlab'],
    source: 'https://google.com',
    visit: 'https://github.com/Menon-Madhav/Digital-Twin',
    id: 1,
  },
  {
    title: 'Stereo-Based Vision Systems',
    description: "Funded project from our Univeristy where I will be working with a Zed 2i Camera for mapping and 3D reconstruction algorithms, Region of Interest finding algorithms for various applications ",
      image: '/images/stereo.png',
      tags: ['OpenCV', 'PyTorch'],
    source: 'https://google.com',
    visit: 'https://github.com/Menon-Madhav/Vision-Systems',
    id: 2,
  },
  {
    title: 'Multibody Analysis of Suspension',
    description: "Using Matlab's Simscape Multibody for simulating a double wishbone suspension that can be used in an FSAE vehicle, The simulations will help in tuning the suspensions with very less hastle and  decrease the complexity in designing the suspensions.",
    image: '/images/suspension.png',
    tags: ['Matlab', 'Fusion360'],
    source: 'https://google.com',
    visit: 'https://github.com/Menon-Madhav/MultiBody-Analysis',
    id: 3,
  },
  {
    title: 'CFD Project',
    description: "Using Open Source softwares like OpenFoam and gmsh to simulate liquid flow through a provided vessel(eg:-Nozzle). This project is part of my coursework for Numerical Fluid Flow & Heat Transfer.",
    image: '/images/CFD.png',
    tags: ['OpenFoam', 'Gmsh', ],
    source: 'https://google.com',
    visit: 'https://github.com/Menon-Madhav/CFD',
    id: 4,
  },
  {
    title: 'Self-Cleaning Surfaces',
    description: "Study-oriented project where I am going over various papers, journals to compile various resources regarding self-cleaning surfaces, there types their make and how to implement them, This is part of my coursework for Non-Traditional Processes. ",
    image: '/images/self-cleaning.png',
    tags: ['None'],
    source: 'https://google.com',
    visit: 'https://github.com/Menon-Madhav/Self-Cleaning-Surfaces',
    id: 5,
  },
  {
    title: 'Cycloidal drive',
    description: "The study on Harmonic and Cycloidal drives that I had done as part of my internship, It also has the CAD models of the cycloidal drive that I had designed ",
    image: '/images/cycloidal.png',
    tags: ['Autodesk Inventor', 'Matlab'],
    source: 'https://google.com',
    visit: 'https://github.com/Menon-Madhav/Cycloidal-Gears',
    id: 6,
  },
];

export const TimeLineData = [
  { year: "2017", text: 'Started coding from my 8th Grade', },
  { year: "Aug, 2019", text: 'My College Life starts, I meet new people learn about various streams that I can get into ', },
  { year: "Dec, 2019", text: 'Started taking online courses to develop my skill around robotics, simulations', },
  { year: "Apr, 2021", text: 'I start my work on the autonomous mobile robot with CRISS', },
  { year: "June, 2021", text: 'My Internship at MTAB begins, my first professional experience', },
];